import type { LocalizedDocsPage } from "./types";

// Scenario 1: verification of the demo app. Unlike the other scenarios it does not switch on a module;
// it runs the repository's test tools against the running apps stack. Structure, in both locales:
// an overview, then one section per test tool with "how to check the result" and "evaluation"
// subsections, then a cleanup section - the same closing every scenario page has.
export const scenarioTesting: LocalizedDocsPage = {
  en: {
    title: "Scenario 1: Verify the demo app",
    description:
      "This scenario verifies the operation of the demo application - the apps stack - with the test tools in " +
      "this repository: unit, end-to-end, contract, load and security. Each tool has its own make command and " +
      "produces an HTML report. The screenshots on this page are reports generated by these commands against " +
      "this repository.",
    sections: [
      {
        heading: "Overview",
        body: [
          "The same running apps stack is verified from several angles, each by a separate open-source tool. " +
            "For each tool, this page describes how to check its results and how those results are evaluated.",
          "shared/openapi/openapi.yaml is maintained by hand rather than generated from the code, so it can diverge " +
            "from the implementation, which is what makes checking it worthwhile. Specmatic verifies the provider " +
            "side (the real backend answers as the contract specifies) and serves a mock for the consumer side " +
            "(the frontend's calls are made against a mock built from the same file, with no real backend). " +
            "Kong can route the frontend to that mock without a " +
            "frontend change ([Scenario 2](/docs/scenario-kong)); agentgateway builds its MCP tools from the same " +
            "file ([Scenario 7](/docs/scenario-agentgateway)).",
          "Every test command leaves an HTML report (git-ignored, regenerated on each run). Open the file " +
            "directly in a browser, or serve its folder with python3 -m http.server.",
        ],
        table: {
          headers: ["Layer", "Tool", "What it checks"],
          nowrapColumns: [0, 1],
          rows: [
            ["Unit (backend)", "pytest", "22 tests: accounts and balances, password login, profile, Keycloak JWT validation (including forged and tampered tokens). Uses an in-memory database."],
            ["Unit (frontend)", "Vitest", "20 tests: the API client, the OIDC PKCE flow, and the backend resolver (round robin, fallback to the next instance)."],
            ["End to end", "Playwright", "9 tests in a real browser: login and logout, profile, a wrong password, the frontend server's resolver API."],
            ["Contract (provider)", "Specmatic", "20 scenarios: does the real backend honour openapi.yaml? 100% of paths, methods and response codes covered."],
            ["Contract (consumer)", "Vitest + Specmatic mock", "Using 9 tests verifies if the frontend's own API usage hold up against a mock built from the same contract?"],
            ["Load", "Locust", "HTTP, GraphQL and MySQL scenarios, an overload scenario, and the same overload sent through Kafka."],
            ["Security", "OWASP ZAP", "A passive scan of the frontend, an active scan, and an OpenAPI-driven scan of every backend route."],
          ],
        },
        note:
          "The unit tests require no running services and can be run first: make pytest:test and " +
          "make vitest:test. make all:test runs pytest, Vitest, Playwright and Specmatic in sequence, starting " +
          "the apps stack beforehand. On GitHub, CI runs backend and frontend unit tests and consumer and provider " +
          "contract tests in four parallel jobs, alongside lint, build, type and configuration checks. Each contract " +
          "job starts its own required services, and test reports are uploaded as workflow artifacts.",
      },
      {
        heading: "pytest: backend unit tests",
        subsections: [
          {
            heading: "Checking the results",
            body: [
              "pytest replaces MySQL with an in-memory database, so it needs no other service and completes in " +
                "under a second. The report is a single self-contained file: pytest/report/report.html.",
            ],
            code: [{ code: "make pytest:test" }],
            images: [
              {
                src: "/docs/screenshots/report-pytest.png",
                alt: "pytest-html report: an environment table and a summary listing the backend tests, all passed",
                caption: "pytest: one self-contained report.html with the environment and a pass/fail row per test.",
              },
            ],
          },
          {
            heading: "Evaluation",
            body: [
              "All 22 tests pass. They cover accounts and balances, password login, the profile, and Keycloak JWT " +
                "validation, including forged and tampered tokens.",
            ],
          },
        ],
      },
      {
        heading: "Vitest: frontend unit tests",
        subsections: [
          {
            heading: "Checking the results",
            body: [
              "Vitest tests the frontend's logic without a browser: the API client, the PKCE handling of the login " +
                "redirect, and the server-side resolver that selects the backend to forward to. It replaces fetch, " +
                "so apps:up is not needed. The report is vitest/report/index.html.",
            ],
            code: [{ code: "make vitest:test" }],
            images: [
              {
                src: "/docs/screenshots/report-vitest.png",
                alt: "Vitest HTML report: 20 passed, 0 failed, with the test tree of api.test.ts, oidc.test.ts and backendResolver.test.ts on the left",
                caption: "Vitest: a dashboard (20 passed) and a browsable tree of every test, grouped by file.",
              },
            ],
          },
          {
            heading: "Evaluation",
            body: [
              "All 20 tests pass, with no failures. They cover the API client, the OIDC PKCE flow, and the backend " +
                "resolver, including round robin and fallback to the next instance.",
            ],
          },
        ],
      },
      {
        heading: "Playwright: end-to-end tests",
        subsections: [
          {
            heading: "Checking the results",
            body: [
              "Playwright drives the real frontend in a browser against the real backend and MySQL, so the apps " +
                "stack must be running. The report is playwright/report/index.html; for a failed test, the trace " +
                "(screenshots, network and console) is available from the report.",
            ],
            code: [{ code: "make apps:up\nmake playwright:test" }],
            images: [
              {
                src: "/docs/screenshots/report-playwright.png",
                alt: "Playwright HTML report listing the 9 end-to-end tests as passed, with durations",
                caption: "Playwright: one row per test with its duration.",
              },
            ],
          },
          {
            heading: "Evaluation",
            body: [
              "All 9 tests pass in a real browser: login and logout, the profile, a wrong password, and the " +
                "frontend server's resolver API.",
            ],
          },
        ],
      },
      {
        heading: "Specmatic: contract tests",
        subsections: [
          {
            heading: "Checking the results",
            body: [
              "Specmatic reads shared/openapi/openapi.yaml and sends requests to the running backend (run make apps:up first), then reports coverage per " +
                "path, method and response code, including the error responses (401, 404, 422) that the normal " +
                "flow does not reach. The report is specmatic/report/test/html/index.html (HTML and JUnit files).",
              "The consumer side is checked against a mock built from the same contract: the frontend's own API " +
                "calls run against it; the mock reads the contract and examples from shared/openapi, so only the mock needs to be " +
                "started (not the apps stack). The tests compare complete response values and error bodies. " +
                "Its report is vitest/report-contract/index.html.",
            ],
            code: [
              { label: "Provider", code: "make apps:up\nmake specmatic:test" },
              { label: "Consumer", code: "make specmatic:mock-up\nmake vitest:contract-test" },
            ],
            images: [
              {
                src: "/docs/screenshots/report-specmatic.png",
                alt: "Specmatic contract test results: 100% API coverage, 20 successes, and a table of every path, method and response code marked Covered",
                caption: "Specmatic: 20 of 20 scenarios passed, 100% API coverage, broken down by path, method and response code.",
              },
            ],
          },
          {
            heading: "Evaluation",
            body: [
              "All 20 scenarios pass, and 100% of paths, methods and response codes are covered. The scenarios are " +
                "the requests built from the contract plus 15 examples checked in next to it (shared/openapi/examples), " +
                "so the error cases and the authenticated calls are exercised as well.",
            ],
          },
        ],
      },
      {
        heading: "Locust: load tests",
        subsections: [
          {
            heading: "Checking the results",
            body: [
              "Locust runs against the running apps stack (make apps:up first) and reports response times and failures per endpoint. The available scenarios are HTTP, GraphQL " +
                "and MySQL, an overload scenario, and the same overload sent through Kafka; [Scenario 3](/docs/scenario-kafka) " +
                "and [Scenario 4](/docs/scenario-observability) use it to show the effect of an overload and how " +
                "Kafka and observability each respond. The report is locust/logs/<timestamp>/report.html.",
            ],
            code: [{ code: "make apps:up\nmake locust:test LOCUST_FILE=locustfile_http.py LOCUST_USERS=10 LOCUST_SPAWN_RATE=5 LOCUST_RUN_TIME=20s" }],
            images: [
              {
                src: "/docs/screenshots/report-locust.png",
                alt: "Locust test report: a 20-second run of locustfile_http.py against http://backend:8080 with 97 requests, 0 failures, and response time percentiles per endpoint",
                caption: "Locust: request statistics and response-time percentiles per endpoint (a short 10-user, 20-second run: 97 requests, 0 failures).",
              },
            ],
          },
          {
            heading: "Evaluation",
            body: [
              "The sample run (10 users, 20 seconds, locustfile_http.py against the backend) completed 97 requests " +
                "with no failures. The report gives the request statistics and the response-time percentiles for " +
                "each endpoint.",
            ],
          },
        ],
      },
      {
        heading: "OWASP ZAP: security scans",
        subsections: [
          {
            heading: "Checking the results",
            body: [
              "Both scans need the apps stack running (make apps:up first). make zap:baseline runs a passive scan of the frontend. make zap:api-scan runs an OpenAPI-driven scan " +
                "that sends real attack payloads to every backend route, so it only ever targets the apps stack. " +
                "Each scan writes zap/report/<scan>-report.html.",
            ],
            code: [{ code: "make apps:up\nmake zap:baseline\nmake zap:api-scan" }],
            images: [
              {
                src: "/docs/screenshots/report-zap.png",
                alt: "ZAP scanning report for http://backend:8080: no High or Medium alerts, 2 Low, 5 informational, 27 endpoints",
                caption: "ZAP api-scan of the backend: 27 endpoints, no High or Medium alerts (2 Low). The scan passed 116 rules with 0 failures and 2 warnings.",
              },
            ],
            note:
              "There's also make zap:full-scan, a deeper active scan of the frontend itself - deliberately left out of the walkthrough above. Its attack payloads against the frontend's many hashed _next/static/* asset URLs can drive the Next.js dev server (Turbopack) into a CPU-pinning recompile loop that doesn't recover on its own, even after the scan stops. If that happens, restart just the frontend: docker compose -p apps -f apps/docker-compose.yml restart frontend.",
          },
          {
            heading: "Evaluation",
            body: [
              "The api-scan of the backend covered 27 endpoints and raised no High or Medium alerts (2 Low, 5 " +
                "informational); 116 rules passed, with 0 failures and 2 warnings.",
              "The baseline scan of the frontend, a Next.js development server that is not hardened, passed 52 " +
                "rules and raised 15 warnings, mostly missing security headers, with 0 failures.",
            ],
            note:
              "These are results from a development stack. They demonstrate the tooling and are not a security audit.",
          },
        ],
      },
      {
        heading: "Cleanup",
        body: [
          "Stop the services started for the tests. The reports remain in each tool's report directory (git-ignored) " +
            "until they are regenerated.",
        ],
        code: [{ code: "make specmatic:mock-down\nmake apps:down" }],
      },
    ],
  },
  ja: {
    title: "シナリオ1: デモアプリの動作検証",
    description:
      "このシナリオでは、デモアプリケーション(appsスタック)の動作を、本リポジトリのテストツールで検証します。" +
      "ユニット・E2E・コントラクト・負荷・セキュリティの各テストは、それぞれ専用のmakeコマンドを持ち、" +
      "HTMLレポートを出力します。本ページのスクリーンショットは、これらのコマンドを本リポジトリに対して" +
      "実行して生成した実際のレポートです。",
    sections: [
      {
        heading: "概要",
        body: [
          "同じ稼働中のappsスタックを、それぞれ別のオープンソースのツールで、複数の観点から検証します。" +
            "本ページでは、ツールごとに、結果の確認方法と、その結果の評価を記載します。",
          "shared/openapi/openapi.yamlはコードから生成せず手で保守しているため、実装と食い違う可能性があり、" +
            "それが確認する意味を生みます。Specmaticはプロバイダー側(実際のbackendがコントラクトどおりに" +
            "応答するか)を検証し、コンシューマー側にはmockを提供します(frontendの呼び出しを、同じファイルから" +
            "作ったモックに対して行い、実際のbackendは使いません)。" +
            "Kongはfrontendを変更せずに、そのモックへ経路を切り替えられます([シナリオ2](/docs/scenario-kong))。" +
            "agentgatewayも、同じファイルからMCPツールを作ります([シナリオ7](/docs/scenario-agentgateway))。",
          "どのテストコマンドも、HTMLレポートを出力します(gitignore対象で、実行のたびに再生成されます)。" +
            "ファイルをブラウザで直接開くか、フォルダをpython3 -m http.serverで配信して参照します。",
        ],
        table: {
          headers: ["レイヤー", "ツール", "確認すること"],
          nowrapColumns: [0, 1],
          rows: [
            ["ユニット(backend)", "pytest", "22件: 口座と残高、パスワードログイン、プロフィール、KeycloakのJWT検証(偽造・改ざんトークンを含む)。インメモリDBを使う。"],
            ["ユニット(frontend)", "Vitest", "20件: APIクライアント、OIDCのPKCEフロー、backend resolver(ラウンドロビンと次のインスタンスへのフォールバック)。"],
            ["E2E", "Playwright", "実ブラウザで9件: ログイン・ログアウト、プロフィール、誤ったパスワード、frontendサーバーのresolver API。"],
            ["コントラクト(プロバイダー)", "Specmatic", "20シナリオ: 実際のbackendがopenapi.yamlどおりに応答するか。パス・メソッド・レスポンスコードの100%をカバー。"],
            ["コントラクト(コンシューマー)", "Vitest + Specmaticのmock", "frontend自身のAPI利用が、同じコントラクトから作ったモックに対して成立するか。"],
            ["負荷", "Locust", "HTTP・GraphQL・MySQLのシナリオ、overloadシナリオ、同じ負荷をKafka経由にしたもの。"],
            ["セキュリティ", "OWASP ZAP", "frontendのパッシブスキャン、アクティブスキャン、backendの全ルートを対象にしたOpenAPI駆動のスキャン。"],
          ],
        },
        note:
          "ユニットテストは稼働中のサービスを必要とせず、最初に実行できます: make pytest:test と make vitest:test。" +
          "make all:test は、pytest・Vitest・Playwright・Specmaticを順に実行します(先にappsスタックを起動します)。" +
          "GitHubのCIは、lint・ビルド・型・設定のチェックに加え、backendとfrontendのユニットテスト、" +
          "コンシューマーとプロバイダーのコントラクトテストを4つのジョブで並列実行します。" +
          "各コントラクトテストのジョブが必要なサービスを起動し、テストレポートをワークフローのartifactとして保存します。",
      },
      {
        heading: "pytest: backendのユニットテスト",
        subsections: [
          {
            heading: "確認方法",
            body: [
              "pytestはMySQLをインメモリDBに差し替えるため、ほかのサービスを必要とせず、1秒未満で完了します。" +
                "レポートは自己完結した1つのファイル pytest/report/report.html です。",
            ],
            code: [{ code: "make pytest:test" }],
            images: [
              {
                src: "/docs/screenshots/report-pytest.png",
                alt: "pytest-htmlのレポート。環境情報の表と、すべてPassedになったbackendのテスト一覧",
                caption: "pytest: 自己完結した1つのreport.html。環境情報と、テストごとの合否の行。",
              },
            ],
          },
          {
            heading: "評価結果",
            body: [
              "22件すべてが成功しました。対象は、口座と残高、パスワードログイン、プロフィール、KeycloakのJWT検証" +
                "(偽造・改ざんされたトークンを含む)です。",
            ],
          },
        ],
      },
      {
        heading: "Vitest: frontendのユニットテスト",
        subsections: [
          {
            heading: "確認方法",
            body: [
              "Vitestはブラウザなしでfrontendのロジックをテストします。対象は、APIクライアント、ログインの" +
                "リダイレクトにおけるPKCEの扱い、転送先のbackendを選ぶサーバー側のresolverです。" +
                "fetchを差し替えるため、apps:upは不要です。レポートは vitest/report/index.html です。",
            ],
            code: [{ code: "make vitest:test" }],
            images: [
              {
                src: "/docs/screenshots/report-vitest.png",
                alt: "VitestのHTMLレポート。20件Pass・0件Failで、左にapi.test.ts・oidc.test.ts・backendResolver.test.tsのテストツリーが表示されている",
                caption: "Vitest: ダッシュボード(20件Pass)と、ファイル別にまとまった全テストのツリー。",
              },
            ],
          },
          {
            heading: "評価結果",
            body: [
              "20件すべてが成功し、失敗はありません。対象は、APIクライアント、OIDCのPKCEフロー、backend resolver" +
                "(ラウンドロビンと次のインスタンスへのフォールバックを含む)です。",
            ],
          },
        ],
      },
      {
        heading: "Playwright: E2Eテスト",
        subsections: [
          {
            heading: "確認方法",
            body: [
              "Playwrightは、実際のfrontendをブラウザで動かし、実際のbackendとMySQLに対して操作するため、" +
                "appsスタックを起動しておく必要があります。レポートは playwright/report/index.html で、" +
                "失敗したテストについては、レポートからトレース(スクリーンショット・ネットワーク・コンソール)を" +
                "参照できます。",
            ],
            code: [{ code: "make apps:up\nmake playwright:test" }],
            images: [
              {
                src: "/docs/screenshots/report-playwright.png",
                alt: "PlaywrightのHTMLレポート。9件のE2Eテストがpassedで、所要時間とともに一覧されている",
                caption: "Playwright: テストごとに1行と所要時間。",
              },
            ],
          },
          {
            heading: "評価結果",
            body: [
              "実ブラウザでの9件すべてが成功しました。対象は、ログイン・ログアウト、プロフィール、誤ったパスワード、" +
                "frontendサーバーのresolver APIです。",
            ],
          },
        ],
      },
      {
        heading: "Specmatic: コントラクトテスト",
        subsections: [
          {
            heading: "確認方法",
            body: [
              "Specmaticはshared/openapi/openapi.yamlを読み、稼働中のbackendへ(先にmake apps:up)リクエストを送って、パス・メソッド・レスポンスコード" +
                "ごとのカバレッジを報告します。正常系では届かないエラーレスポンス(401・404・422)も含みます。" +
                "レポートは specmatic/report/test/html/index.html です(HTMLとJUnitのファイル)。",
              "コンシューマー側は、同じコントラクトから作ったmockに対して、frontend自身のAPI呼び出しを実行して" +
                "確認します。mockはshared/openapiのコントラクトとexampleを読むため、mockだけ起動すれば足ります(appsスタックは不要)。" +
                "テストは、レスポンスの全値とエラーの本文を比較します。" +
                "レポートは vitest/report-contract/index.html です。",
            ],
            code: [
              { label: "プロバイダー", code: "make apps:up\nmake specmatic:test" },
              { label: "コンシューマー", code: "make specmatic:mock-up\nmake vitest:contract-test" },
            ],
            images: [
              {
                src: "/docs/screenshots/report-specmatic.png",
                alt: "Specmaticのコントラクトテスト結果。APIカバレッジ100%、成功20件で、全パス・メソッド・レスポンスコードがCoveredの表",
                caption: "Specmatic: 20シナリオ中20件が成功、APIカバレッジ100%。パス・メソッド・レスポンスコード別の内訳付き。",
              },
            ],
          },
          {
            heading: "評価結果",
            body: [
              "20シナリオすべてが成功し、パス・メソッド・レスポンスコードの100%をカバーしました。シナリオは、" +
                "コントラクトから作ったリクエストと、同じ場所(shared/openapi/examples)にチェックインした15個のexampleで構成されるため、" +
                "エラーケースと認証つきの呼び出しも実行されます。",
            ],
          },
        ],
      },
      {
        heading: "Locust: 負荷テスト",
        subsections: [
          {
            heading: "確認方法",
            body: [
              "Locustは、稼働中のappsスタック(先にmake apps:up)に対して実行し、エンドポイントごとの応答時間と失敗を報告します。用意されているシナリオは、HTTP・GraphQL・MySQL、" +
                "overloadシナリオ、同じ負荷をKafka経由にしたものです。[シナリオ3](/docs/scenario-kafka)と" +
                "[シナリオ4](/docs/scenario-observability)は、これを使って、過負荷が何を起こし、Kafkaとオブザーバビリティが" +
                "それぞれどう応えるかを示します。レポートは locust/logs/<タイムスタンプ>/report.html です。",
            ],
            code: [{ code: "make apps:up\nmake locust:test LOCUST_FILE=locustfile_http.py LOCUST_USERS=10 LOCUST_SPAWN_RATE=5 LOCUST_RUN_TIME=20s" }],
            images: [
              {
                src: "/docs/screenshots/report-locust.png",
                alt: "Locustのテストレポート。http://backend:8080に対するlocustfile_http.pyの20秒間の実行で、97リクエスト・失敗0件と、エンドポイントごとの応答時間パーセンタイル",
                caption: "Locust: エンドポイントごとのリクエスト統計と応答時間のパーセンタイル(10ユーザー・20秒の短い実行: 97リクエスト、失敗0件)。",
              },
            ],
          },
          {
            heading: "評価結果",
            body: [
              "サンプルの実行(10ユーザー、20秒、backendに対するlocustfile_http.py)では、97リクエストが失敗なく" +
                "完了しました。レポートには、エンドポイントごとのリクエスト統計と応答時間のパーセンタイルが" +
                "示されます。",
            ],
          },
        ],
      },
      {
        heading: "OWASP ZAP: セキュリティスキャン",
        subsections: [
          {
            heading: "確認方法",
            body: [
              "どちらのスキャンも、稼働中のappsスタックが必要です(先にmake apps:up)。make zap:baselineは、frontendのパッシブスキャンを実行します。make zap:api-scanは、OpenAPI駆動の" +
                "スキャンで、backendの全ルートへ実際の攻撃ペイロードを送るため、対象は常にappsスタックだけです。" +
                "どちらのスキャンも zap/report/<スキャン名>-report.html を出力します。",
            ],
            code: [{ code: "make apps:up\nmake zap:baseline\nmake zap:api-scan" }],
            images: [
              {
                src: "/docs/screenshots/report-zap.png",
                alt: "http://backend:8080に対するZAPのスキャンレポート。HighとMediumのアラートはなく、Lowが2件、Informationalが5件、エンドポイント数は27",
                caption: "backendのZAP api-scan: 27エンドポイントでHigh・Mediumのアラートなし(Lowが2件)。116ルールに合格し、失敗0件・警告2件。",
              },
            ],
            note:
              "make zap:full-scanというコマンドもあります。frontend自体に対するより踏み込んだアクティブスキャンですが、上記のウォークスルーからは意図的に外しています。frontendの大量のハッシュ付き _next/static/* アセットURLへの攻撃ペイロードが、Next.jsの開発サーバー(Turbopack)を再コンパイル/キャッシュ書き換えの無限ループに陥らせ、スキャンを止めた後もCPUが張り付いたまま回復しないことがあるためです。発生した場合は frontend コンテナだけを再起動してください: docker compose -p apps -f apps/docker-compose.yml restart frontend",
          },
          {
            heading: "評価結果",
            body: [
              "backendのapi-scanは27エンドポイントを対象とし、HighとMediumのアラートはありませんでした(Lowが2件、" +
                "Informationalが5件)。116ルールに合格し、失敗は0件、警告は2件でした。",
              "frontend(強化されていないNext.jsの開発サーバー)のベースラインスキャンは、52ルールに合格し、" +
                "15件で警告(多くはセキュリティヘッダーの欠如)、失敗は0件でした。",
            ],
            note:
              "開発用スタックでの結果です。ツールの実演であり、セキュリティ監査ではありません。",
          },
        ],
      },
      {
        heading: "環境のクリーンアップ",
        body: [
          "テストのために起動したサービスを停止します。レポートは、再生成されるまで各ツールのレポートディレクトリに" +
            "残ります(gitignore対象)。",
        ],
        code: [{ code: "make specmatic:mock-down\nmake apps:down" }],
      },
    ],
  },
};
